[package]
name = "axsum-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = {path = "./api"}
sea-orm = "0.12.3"

[workspace]
members = [".", "api", "service", "entity", "migration"]
